# Generated by Django 4.2.1 on 2023-05-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photo_artist_name_alter_urequesr_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='artistname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
