# Generated by Django 4.2.1 on 2023-05-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_artistname'),
    ]

    operations = [
        migrations.AddField(
            model_name='urequesr',
            name='artistname',
            field=models.CharField(default='artist', max_length=100),
        ),
    ]
